valor01 = float (input ("Entre com um valor"))
valor02 = float (input ("Entre com um valor"))
soma = valor01 + valor02
print ("\n",valor01, "+" ,valor02, "=", soma)
sub = valor01 - valor02
print ("\n",valor01, "-" ,valor02, "=", sub)
multi = valor01 * valor02
print ("\n",valor01, "*", valor02, "=", multi)
divi = round(valor01 / valor02)
print ("\n", valor01, "/", valor02, "=", divi)
